# theme: bulma-clean-theme
remote_theme: chrisrhymes/bulma-clean-theme@v0.14.0

title: Nevis Neutrino Wiki
tagline: Nevis Neutrino Wiki
description: A wiki for documentation of Nevis Neutrino Computing.
baseurl: "" # the subpath of your site, e.g. /blog
# favicon: /images/sbn_logo.jpg

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-github-metadata
  - kramdown
  - rouge
  - jekyll-site-tree

exclude:
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass

#google_analytics: UA-code-here

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: false
      hero_height: is-small
      # favicon: /images/sbn_logo.jpg
      hero_height: is-small
      show_sidebar: false
      lang: en
      hide_footer: true
  # -
    # scope:
    #   path: ""
    #   type: "posts"
    # values:
    #   author: "C.S. Rhymes"
    #   layout: post
    #   image: https://via.placeholder.com/1200x800
    #   show_sidebar: true

markdown: kramdown
highlighter: rouge
syntax_highlighter: rouge

site_tree.file: map.md
# site_tree.collapse = true
# hide status error pages (404.html, 287.html, ...) & any js, css, json... files from the site tree.
# site_tree.exclude:
#   - /\d+\.[^\/]+$
#   - \.(js|css|json|xml|png|jpeg|jpg|art|ant|ico)$

footer_menu: example_footer_menu

collections:
  # products:
  #   output: true
  #   layout: product
  #   image: https://via.placeholder.com/800x600
  #   show_sidebar: false
